include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for pi-relay-control
LUCI_DEPENDS:=+luci-base +pi-relay-control +rpcd

PKG_MAINTAINER:=Jaco Hanekom <jhanekom@gmail.com>
PKG_LICENSE:=custom

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
